apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "staysafePublicSite.secretStoreName" . }}
  labels:
    {{- include "staysafePublicSite.labels" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcpSecrets.projectId | quote }}
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: {{ .Values.gcpSecrets.auth.secretRef.name | quote }}
            key: {{ .Values.gcpSecrets.auth.secretRef.key | quote }}
            namespace: {{ .Release.Namespace | quote }}
