apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "staysafePublicSite.imagePullName" . }}
  labels:
    {{- include "staysafePublicSite.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "staysafePublicSite.secretStoreName" . }}
  target:
    name: {{ include "staysafePublicSite.imagePullName" . }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .dockerConfigJson }}` }}"
  data:
    - secretKey: dockerConfigJson
      remoteRef:
        key: {{ .Values.externalSecrets.imagePull.remoteKey | quote }}
        version: {{ .Values.externalSecrets.imagePull.version | quote }}
